import {
  ShoppingCart, Home, Zap, Utensils, Car, Film, ShoppingBag,
  Heart, Plane, Briefcase, Laptop, Gift, Plus, Tag, Music,
  Book, Dumbbell, Coffee, PawPrint, Wifi, Gamepad2, Gem,
  GraduationCap, Stethoscope, MoreHorizontal,
  Apple, Baby, Banknote, Beer, Bike, Bus, Calendar, Camera,
  Clock, Cloud, Compass, CreditCard, DollarSign, Eye, Flower,
  Frown, Headphones, Key, Landmark, Lightbulb, Map, Monitor,
  Moon, Palette, Phone, Pill, Scissors, Shirt, Smartphone,
  Smile, Sofa, Star, Store, Sun, Train, Trees, Trophy,
  Tv, Wine, type LucideIcon,
} from "lucide-react"

const iconMap: Record<string, LucideIcon> = {
  "shopping-cart": ShoppingCart,
  home: Home,
  zap: Zap,
  utensils: Utensils,
  car: Car,
  film: Film,
  "shopping-bag": ShoppingBag,
  "heart-pulse": Heart,
  plane: Plane,
  briefcase: Briefcase,
  laptop: Laptop,
  gift: Gift,
  plus: Plus,
  tag: Tag,
  music: Music,
  book: Book,
  dumbbell: Dumbbell,
  coffee: Coffee,
  "paw-print": PawPrint,
  wifi: Wifi,
  "gamepad-2": Gamepad2,
  gem: Gem,
  "graduation-cap": GraduationCap,
  stethoscope: Stethoscope,
  "more-horizontal": MoreHorizontal,
  apple: Apple,
  baby: Baby,
  banknote: Banknote,
  beer: Beer,
  bike: Bike,
  bus: Bus,
  calendar: Calendar,
  camera: Camera,
  clock: Clock,
  cloud: Cloud,
  compass: Compass,
  "credit-card": CreditCard,
  "dollar-sign": DollarSign,
  eye: Eye,
  flower: Flower,
  frown: Frown,
  headphones: Headphones,
  key: Key,
  landmark: Landmark,
  lightbulb: Lightbulb,
  map: Map,
  monitor: Monitor,
  moon: Moon,
  palette: Palette,
  phone: Phone,
  pill: Pill,
  scissors: Scissors,
  shirt: Shirt,
  smartphone: Smartphone,
  smile: Smile,
  sofa: Sofa,
  star: Star,
  store: Store,
  sun: Sun,
  train: Train,
  tree: Trees,
  trophy: Trophy,
  tv: Tv,
  wine: Wine,
}

export const CATEGORY_ICONS = Object.keys(iconMap)

export function getCategoryIcon(name: string | null, size = 16): React.ReactNode {
  if (!name) return null
  const Icon = iconMap[name]
  if (!Icon) return null
  return <Icon size={size} />
}
